# This is a basic workflow to help you get started with Actions

name: Java Maven SAST CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: cdefense/sast-scan
      options: -v /__w/vulnerable-java-maven/vulnerable-java-maven/target:/app -e "WORKSPACE=/__w/vulnerable-java-maven/vulnerable-java-maven"
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

      # Build with Maven
    - name: Build with Maven
      run: mvn clean install
      
      # Run SAST scan
    - name: SAST Scan
      run: python3 /usr/local/src/scan --src /app --type java --app_name vulnerable-java-maven --api-key 75a81a24-adfc-4bfd-8b32-7562169a9759
